services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_LOGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
    - "5433:5432"
    volumes:
    - pgdb:/var/lib/postgresql/data
    networks:
    - fastapi_net

  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
     - .:/usr/src/app
    ports:
    - "8002:8000"
    depends_on:
     - pgdb
    links:
    - pgdb:pgdb
    networks:
    - fastapi_net

networks:
    fastapi_net:
      driver: bridge

volumes:
  pgdb: